zstyle :plugin:fast-syntax-highlighting theme "roboslone"
typeset -g FAST_THEME_NAME="roboslone"
: ${FAST_HIGHLIGHT_STYLES[roboslonedefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[robosloneunknown-token]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[roboslonereserved-word]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonealias]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonesuffix-alias]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonebuiltin]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonefunction]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonecommand]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[robosloneprecommand]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonecommandseparator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonehashed-command]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonepath]:=underline}
: ${FAST_HIGHLIGHT_STYLES[roboslonepath_pathseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[robosloneglobbing]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[robosloneglobbing-ext]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[roboslonehistory-expansion]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[roboslonesingle-hyphen-option]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[roboslonedouble-hyphen-option]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[robosloneback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonesingle-quoted-argument]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[roboslonedouble-quoted-argument]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[roboslonedollar-quoted-argument]:=fg=white}
: ${FAST_HIGHLIGHT_STYLES[robosloneback-or-dollar-double-quoted-argument]:=fg=white}
: ${FAST_HIGHLIGHT_STYLES[robosloneback-dollar-quoted-argument]:=fg=white}
: ${FAST_HIGHLIGHT_STYLES[robosloneassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[robosloneredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonecomment]:=fg=black}
: ${FAST_HIGHLIGHT_STYLES[roboslonevariable]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonemathvar]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonemathnum]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonematherr]:=none}
: ${FAST_HIGHLIGHT_STYLES[robosloneassign-array-bracket]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonefor-loop-variable]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonefor-loop-number]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonefor-loop-operator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonefor-loop-separator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[robosloneexec-descriptor]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonehere-string-tri]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonehere-string-text]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonehere-string-var]:=fg=white}
: ${FAST_HIGHLIGHT_STYLES[roboslonesecondary]:=default}
: ${FAST_HIGHLIGHT_STYLES[roboslonecase-input]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonecase-parentheses]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonecase-condition]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonecorrect-subtle]:=none}
: ${FAST_HIGHLIGHT_STYLES[robosloneincorrect-subtle]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonesubtle-separator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonesubtle-bg]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonepath-to-dir]:=underline}
: ${FAST_HIGHLIGHT_STYLES[roboslonepaired-bracket]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonebracket-level-1]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonebracket-level-2]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonebracket-level-3]:=none}
: ${FAST_HIGHLIGHT_STYLES[robosloneglobal-alias]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonesubcommand]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[roboslonesingle-sq-bracket]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonedouble-sq-bracket]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonedouble-paren]:=none}
: ${FAST_HIGHLIGHT_STYLES[robosloneoptarg-string]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[robosloneoptarg-number]:=none}
: ${FAST_HIGHLIGHT_STYLES[roboslonerecursive-base]:=none}
