source ~/.config/dotfiles/zsh/common.zsh

if [[ -e ~/.zshrc.local ]]; then
    source ~/.zshrc.local
fi
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/roboslone/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
